# Generated by Django 2.0.3 on 2018-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2)),
                ('location', models.CharField(blank=True, help_text='Location to drop off opioids', max_length=200)),
                ('location_link', models.URLField(blank=True, help_text='Google Maps link to location', max_length=500)),
            ],
        ),
    ]
